### ISSUE TITLE
[Task]: Retrieve saved password to remote machine

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/rustdesk#26]
Or something to copy access to another computer.

<details>
<summary>Currently have <code>/root/.config/rustdesk/RustDesk.toml</code>:</summary>

```toml
enc_id = 'CENSORED'
password = 'CENSORED'
salt = 'CENSORED'
key_pair = [
    [
    202,
    77,
    CENSORED
],
    [
    254,
    215,
    CENSORED
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
```
</details>

Source: https://github.com/rustdesk/rustdesk/issues/69#issuecomment-1220015247

`RustDesk` > `Settings` > `Security` > `Password` > `Use permanent password` > `Set permanent password` shows a given length (possibly correct length) `*` password matching `digit`, `uppercase`, `lowercase`, `length>=8` but <kbd>ctrl</kbd> + <kbd>c</kbd> does not actually copy the password to the clipboard.

I finally reset the password as a workaround.

+5

### Are you our team member?

- [X] Yes, I am?

**Comment by Benjamin-Loison** [comment]
Related to #40.

**Comment by Benjamin-Loison** [comment]
```bash
sudo rustdesk --config enc_id
```

```bash
sudo rustdesk --config `tomlq -r .enc_id ~/.config/rustdesk/RustDesk.toml`
```

and

```bash
sudo rustdesk --config 'CENSORED'
```

do not return anything.

**Comment by Benjamin-Loison** [comment]
https://www.reddit.com/r/rustdesk/comments/15w6yx1/transferring_connections_and_saved_passwords_to_a/

**Comment by Benjamin-Loison** [comment]
https://rustdesk.com/docs/en/self-host/client-configuration/#3-setup-using-import-or-export

https://rustdesk.com/docs/en/self-host/client-deployment/

**Comment by Benjamin-Loison** [comment]
My password notebook and password manager do not seem to have working passwords.

**Comment by Benjamin-Loison** [comment]
https://www.reddit.com/r/rustdesk/comments/11dw1tu/transferring_connections_other_pcs/

**Comment by Benjamin-Loison** [comment]
[rustdesk/discussions/4979](https://github.com/rustdesk/rustdesk/discussions/4979)

https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/

Otherwise first page results of *RustDesk retrieve saved password* do not help.

**Comment by Benjamin-Loison** [comment]
```bash
man rustdesk
```
```
No manual entry for rustdesk
```

**Comment by Benjamin-Loison** [comment]
```bash
rustdesk --password
```

Source: https://rustdesk.com/docs/en/client/#command-line-parameters

and

```bash
 echo -n 'CENSORED' | rustdesk --password
```

do not return anything but:

```bash
 rustdesk --password 'CENSORED'
```
```
Installation and administrative privileges required!
```

```bash
 sudo rustdesk --password 'CENSORED'
```
```
Done!
```

So saving and using a new password is not too hard.

**Comment by Benjamin-Loison** [comment]
Except if approve the computer connecting to the other one as able to connect again without providing a password, it seems clear that can't hash the password. However, as *Forget password* is proposed I suspect that it does not involve any Internet interaction, hence the password needs to be stored in plaintext.

**Comment by Benjamin-Loison** [comment]
Note that as a first step assuming access on the remote machine to dump it would be nice.

**Comment by Benjamin-Loison** [comment]
Related to [Benjamin_Loison/Backup_Android_apps/issues/20](https://codeberg.org/Benjamin_Loison/Backup_Android_apps/issues/20).

**Comment by Benjamin-Loison** [comment]
In `/data/data/com.carriez.flutter_hbb/` on my Fairphone 4 LineageOS 22.2:

```bash
find -print | sort | sed 's;[^/]*/;|---;g;s;---|; |;g'
```
<details>
<summary>Output:</summary>

```
.
|---app_flutter
| |---RustDesk
| |---RustDesk.toml
| |---RustDesk2.toml
| |---RustDesk_ab
| |---RustDesk_lan_peers.toml
| |---RustDesk_local.toml
| |---peers
| | |---XXXXXXXXXX.toml
| | |---XXXXXXXXX.toml
| | |---XXXXXXXXX.toml
|---cache
| |---oat_primary
| | |---arm64
| | | |---base.art
|---code_cache
| |---flutter_engine
| | |---a18df97ca57a249df5d8d68cd0820600223ce262
| | | |---skia
| | | | |---93461bed7394e3c554125b0c50b00fb81eea42c6
| | | | | |---05ae9b9d1e4d28b4a4a729654c5f14094f2b1ea9
| | | | | |---11d00b0e8f0d71627c22e65f8829978ff620085e
| | | | | |---1226c24988875d653d27b9a9cdae0c6b8cf13d50
| | | | | |---29c33f4b367fada4e7c955100a6c2f3dfd8557ea
| | | | | |---2bbbb4beb4e5f32a1b49f4a93d65f13f30798ff8
| | | | | |---335d278417743125ac05dc26032e6cf4a19c0ace
| | | | | |---4af2682910b96d8f91af1cd7ebe0d00f90be62c1
| | | | | |---518afbb487509437449a35ffa0f9a2d02ed15392
| | | | | |---5879efb57f742e73ee08ad55c6be19e852d27baf
| | | | | |---5a551daf3d51192724478ed516c3602fe7474765
| | | | | |---5f5dd003eaa24005e7ab14db902f3efb7ca955ae
| | | | | |---5ffc79cf5681441fe86a3f18e8990894967d717c
| | | | | |---6a6b17e42a1cbe7ecc55696c2bdd7a724b8837d5
| | | | | |---70d338766ae20514eca6f5d387445bc8d553f73f
| | | | | |---90cf864beacc3f6b6f12fd0e491a4a3ed299ec2c
| | | | | |---92eb599cb6ccea67ae4b8afd53f8d651157f6013
| | | | | |---ae67dda6ab17be64e90251b8b5b579dc16e74891
| | | | | |---b084e9beb46742ba125e7b8743987d860a67759f
| | | | | |---c1d3148d27a1fd7c9b1215677199eff7ea63ad60
| | | | | |---c2279a2a3e1ac049335a9fe18bce229d6f2b6f35
| | | | | |---cadabf94192b29762842f33febd7641bc56f347c
| | | | | |---de8e57911724b114c7db0d3fcf30f2153841115a
| | | | | |---e240e4b5975c6ad68fe26a08f1ea3402f08ae14d
| | | | | |---f17ec4e6286c3fb2ab7c368367a730d9712a1a4d
| | | | | |---f2557a1c67f824140f0291d468959a4e062a4f59
| | | | | |---sksl
|---databases
|---files
| |---profileInstalled
| |---profileinstaller_profileWrittenFor_lastUpdateTime.dat
|---no_backup
|---shared_prefs
| |---FlutterSharedPreferences.xml
| |---KEY_SHARED_PREFERENCES.xml
| |---flutter_image_picker_shared_preference.xml
```
</details>

**Comment by Benjamin-Loison** [comment]
<details>
<summary><code>XXXXXXXXXX.toml</code>:</summary>

```toml
password = [
    CENSORED
    82,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'low'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
terminal-persistent = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = true
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
sync-init-clipboard = false
trackpad-speed = 100

[options]
swap-left-right-mouse = ''
collapse_toolbar = ''
touch-mode = ''
local_dir = ''
remote_show_hidden = ''
i444 = ''
remote_dir = '{}'
custom-fps = '30'
zoom-cursor = ''
local_show_hidden = ''
codec-preference = 'auto'

[ui_flutter]
canvas = '{"xCursor":1.0,"yCursor":1.0,"xCanvas":0.0,"yCanvas":300.27272727272725,"scale":0.10227272727272728,"currentDisplay":0}'

[info]
username = 'benjamin_loison'
hostname = 'pegasus'
platform = 'Linux'

[transfer]
write_jobs = []
read_jobs = []
```
</details>
